baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Jane Doe"
theme = "anatole"
summarylength = 20
enableEmoji = true
enableRobotsTXT = true
publishDir = "docs/"
# Enable Disqus
#disqusShortname = "Comentario"

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params.utterances]
repo = "AraujoMJ/blogdown"
issueTerm = "pathname"
theme= "preferred-color-scheme"
