baseURL = "https://araujomj.github.io/blogdown/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Jane Doe"
theme = "anatole"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
summarylength = 20
enableEmoji = true
enableRobotsTXT = true
publishDir = "docs/"
# Enable Disqus
#disqusShortname = "Comentario"

# Google Analytics
googleAnalytics = "G-3DFYMBBN16"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params.utterances]
repo = "AraujoMJ/blogdown"
issueTerm = "pathname"
theme= "preferred-color-scheme"
