
title = "Blog do Araujo"
author = "Marcio Araujo"
copyright = "{{ YEAR }}"
description = "Consultoria, conselhos e partilha do conhecimento"
profilePicture = "images/Araujo2.jpg"
keywords = "Estatística, Melhoramento genético de plantas, Melhoramento florestal, Genética quantitativa, Gestão de dados no melhoramento, Planejamento experimental"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Mon, Jan 2, 2006"
contentratio = 0.75
readMore = false

# label =
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/marcio-araujo-aa419972/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/AraujoMJ"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/marcio.araujo04"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:marcio_ok66@hotmail.com"
